version: "3.3"
services:
  contentapi-discord-bridge:
    build: .
    volumes:
      - contentapi-bridge-db:/app/database
    environment:
      CONTENTAPI_DOMAIN: "${CONTENTAPI_DOMAIN}"
      CONTENTAPI_TOKEN: "${CONTENTAPI_TOKEN}"
      DISCORD_TOKEN: "${DISCORD_TOKEN}"
      DB_FILE: "/app/database/bridge.sqlite"
      MARKUP_SERVICE_DOMAIN: "markup-service:3000"

  markup-service:
    build: ./markup

volumes:
  contentapi-bridge-db: # This will hold your SQLite database
