version: "3.3"
services:
  contentapi-discord-bridge:
    build: .
    restart: on-failure
    volumes:
      - contentapi-bridge-db:/app/database
    environment:
      DB_FILE: "/app/database/bridge.sqlite"
      MARKUP_SERVICE_DOMAIN: "markup-service:3000"
    env_file:
      - .env

  markup-service:
    build: ./markup
    restart: on-failure

volumes:
  contentapi-bridge-db: # This will hold your SQLite database
