name: Deploy

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: SpicyPizza/create-envfile@v2.0.3
      with:
        envkey_DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
        envkey_CONTENTAPI_DOMAIN: ${{ secrets.CONTENTAPI_DOMAIN }}
        envkey_CONTENTAPI_TOKEN: ${{ secrets.CONTENTAPI_TOKEN }}

    - uses: alex-ac/github-action-ssh-docker-compose@master
      name: Docker-Compose Remote Deployment
      with:
        ssh_host: ${{ secrets.SSH_HOST }}
        ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
        ssh_user: ${{ secrets.SSH_USER }}
        docker_compose_prefix: docker_deploy
